// <copyright file="EconomyTransaction.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.BasicModel;

using MUnique.OpenMU.Persistence.Json;

/// <summary>
/// A plain implementation of <see cref="EconomyTransaction"/>.
/// </summary>
public partial class EconomyTransaction : MUnique.OpenMU.DataModel.Entities.EconomyTransaction, IIdentifiable, IConvertibleTo<EconomyTransaction>
{
    
    /// <summary>
    /// Gets or sets the identifier of this instance.
    /// </summary>
    public Guid Id { get; set; }
    
    /// <summary>
    /// Gets the raw object of <see cref="Seller" />.
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("seller")]
    public Character RawSeller
    {
        get => base.Seller as Character;
        set => base.Seller = value;
    }

    /// <inheritdoc/>
    [System.Text.Json.Serialization.JsonIgnore]
    public override MUnique.OpenMU.DataModel.Entities.Character Seller
    {
        get => base.Seller;
        set => base.Seller = value;
    }

    /// <summary>
    /// Gets the raw object of <see cref="Buyer" />.
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("buyer")]
    public Character RawBuyer
    {
        get => base.Buyer as Character;
        set => base.Buyer = value;
    }

    /// <inheritdoc/>
    [System.Text.Json.Serialization.JsonIgnore]
    public override MUnique.OpenMU.DataModel.Entities.Character Buyer
    {
        get => base.Buyer;
        set => base.Buyer = value;
    }


    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    /// <inheritdoc/>
    public EconomyTransaction Convert() => this;
}
